# scc-and-creds.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: onload-kmm-sa
  namespace: onload-kmm
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: use-privileged-scc
  namespace: onload-kmm
rules:
- apiGroups: ["security.openshift.io"]
  resources: ["securitycontextconstraints"]
  resourceNames: ["privileged"]
  verbs: ["use"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: use-privileged-scc
  namespace: onload-kmm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: use-privileged-scc
subjects:
- kind: ServiceAccount
  name: onload-kmm-sa
  namespace: onload-kmm
