apiVersion: kmm.sigs.x-k8s.io/v1beta1
kind: Module
metadata:
  name: onload
  namespace: onload-kmm
spec:
  selector:
    kubernetes.io/hostname: "<node>"
    #node-role.kubernetes.io/worker: ""
  moduleLoader:
    serviceAccountName: onload-kmm-sa
    container:
      modprobe:
        moduleName: onload
        args:
          sfc: ""
          sfc_char: ""
          sfc_tune: ""

      kernelMappings:
        - regexp: '^.+$'
          containerImage: >-
            image-registry.openshift-image-registry.svc:5000/onload-kmm/onload-kmod:9.0.2.140-B1-${KERNEL_FULL_VERSION}
          registryTLS:
            insecureSkipTLSVerify: true
          build:
            dockerfileConfigMap:
              name: onload-kmm-dockerfile
              key: dockerfile
            buildArgs:
              - name: SRPM_IMAGE
                value: default-route-openshift-image-registry.apps.<cluster>.<domain>/onload-kmm/onload-srpm:9.0.2.140
            secrets: 
              - name: etc-pki-entitlement
              - name: onload-signing-keys